remove roscpp as an export dependency for the core package
ros-planning/moveit_task_constructor pull request #237
Opened 2021-02-22 13:41 UTC by v4hn

We do use ROS in the background. But there is no need for a public export dependency on it.

This patch also resolves the following catkin_lint issue:

    moveit_task_constructor_core: CMakeLists.txt(17): error: package 'roscpp' must be in CATKIN_DEPENDS in catkin_package()

I also see this other warning which we might want to address, but I'm not convinced it's worth the additional include directives in dependent targets.

    moveit_task_constructor_core: src/CMakeLists.txt(37): warning: target_include_directories() exports external PUBLIC path '${catkin_INCLUDE_DIRS}'

2021-02-22 14:10 UTC, rhaschke requested changes
I'm fine with this change. Please, also remove the return value.

2021-02-22 14:10 UTC, rhaschke commented on core/include/moveit/task_constructor/stage_p.h
> -			ROS_ERROR_STREAM("Tried to add stage '" << name() << "' to two parents");
For consistency, you should also remove the return value. Throwing _and_ returning false doesn't make sense.

2021-02-22 17:51 UTC, v4hn commented
true. done.

2021-02-22 18:45 UTC, rhaschke approved these changes
I thought of a more fundamental change: removing the return value from the function. As you decided to use an exception instead of a return value, that's the logical conclusion for me. I pushed a corresponding change myself.

2021-02-24 10:11 UTC, v4hn commented
> removing the return value from the function.

Makes sense. Most examples use `ContainerBase::add` anyway, and we don't change this one.
Could you please fix the unit tests that broke because of the API change?

2021-02-24 10:58 UTC, rhaschke commented
> Could you please fix the unit tests that broke because of the API change?

Sure. Didn't compile the tests before.

2021-02-24 11:22 UTC, merged